# The URL the site will be built for
title = "ham3l.cloud"
description = "just a description"
base_url = "https://ham3l.cloud"
author = "ham3l"

theme = "ametrine"
compile_sass = true
build_search_index = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
  { name = "categories", feed = true },
]

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["themes/ametrine/sublime"]
highlight_theme = "css"
highlight_themes_css = [
  { theme = "monokai-pro-dark", filename = "syntax-theme-dark.css" },
  { theme = "monokai-pro-light", filename = "syntax-theme-light.css" },
]
render_emoji = false
smart_punctuation = true
lazy_async_image = false
bottom_footnotes = true
external_links_class = "external"
github_alerts = true

[link_checker]
internal_level = "warn"

[search]
index_format = "elasticlunr_json"


[extra]
accent_color = ["hsl(5 100% 84%)", "hsl(4 48% 82%)"]
categories = [
  { name = "Archived", description = "Posts that have been archived due to their age.", color = "purple", icon = "box-arrow-down" },
  { name = "Featured", description = "Posts that are somewhat decently written.", color = "yellow", icon = "star" },
  { name = "Hot", description = "Posts that did numbers compared to others.", color = "red", icon = "fire" },
  { name = "Test", description = "Categories can be set and customized entirely from config, woo-hoo!", color = "green", icon = "feather" },
]

issues_url = "https://github.com/klatschanstalt/website/issues/new"
source_url = "https://github.com/klatschanstalt/website"
show_copy_button = true
show_reading_time = true
show_backlinks = true
date_format = "%d %B %Y"
date_format_long = "%d %B %Y, %R (%Z)"
date_locale = "de_DE"
timezone = "Europe/Berlin"
show_comments_qr = true
csp = [
  { directive = "font-src", domains = [
    "'self'",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "https:",
    "data:",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "https:",
  ] },
  { directive = "script-src", domains = [
    "cloud.umami.is",
  ] },
  { directive = "style-src", domains = [
    "'self'",
    "'unsafe-inline'",
  ] },
  { directive = "frame-src", domains = [
    "www.youtube-nocookie.com",
    "incr.easrng.net",
    "vmst.io",
    "drive.google.com",
  ] },
  { directive = "connect-src", domains = [
    "*.umami.dev",
    "cloud.umami.is",
    "status.cafe",
    "api.lanyard.rest",
    "ws.audioscrobbler.com",
    "discord.com",
    "api.github.com",
    "ntfy.sh",
  ] },
  { directive = "base-uri", domains = [
    "'none'",
  ] },
  { directive = "form-action", domains = [
    "'none'",
  ] },
]

[extra.meta]
favicon = "favicon.ico"
card = "banner.png"


[extra.nav]
icon = "logo.png"
links = [
  { name = "Writing", category = [
    { url = "@/blog/_index.md", name = "Blog", icon = "newspaper-clipping" },
    { url = "@/nanolog/_index.md", name = "Nanolog", icon = "note-pencil" },
    { url = "@/pages/ueber-mich", name = "Über mich", icon = "user" }   # <-- Neu
  ] },
  { name = "Intresting", category = [
    { url = "https://github.com/klatschanstalt", name = "Github", icon = "github-logo" },
    { url = "@/blog/2025-09-22-coding-principles/index.md", name = "Coding Principles", icon = "code" },
  ] },
]

[extra.footer]
# copyright = false
copyright = "© ham3l.cloud, 2021-$YEAR"
show_timestamp = false
show_powered_by = false
socials = [
    { url = "https://discord.com/users/885063317079592960", icon = "discord" },
    { url = "https://github.com/klatschanstalt", icon = "github" },
    { url = "https://reddit.com/u/klatschanstalt", icon = "reddit" },
    { url = "https://x.com/klatschanstalt", icon = "x" },
    { url = "mailto:admin@ham3l.cloud", icon = "gmail" },
]

[extra.debug]
layout = false
no_styles = false
no_emojis = false
